version: "2.4"

services:
  ms-discovery:
    image: ms-discovery:0.0.1
    mem_limit: 200m
    ports:
      - "8763:8763"
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
  ms-config-server:
    image: ms-config-server:0.0.1
    mem_limit: 200m
    ports:
      - "8887:8887"
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
    depends_on:
      ms-discovery:
        condition: service_started
  ms-student:
    image: ms-student:0.0.1
    mem_limit: 200m
    #    ports:
    #    - "6945:6945"
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
      - "ZIPKIN_URI=http://192.168.1.14:9411"
    depends_on:
      ms-discovery:
        condition: service_started
  ms-gateway:
    image: ms-gateway:0.0.1
    mem_limit: 200m
    ports:
      - "8181:8181"
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
      - "ZIPKIN_URI=http://192.168.1.14:9411"
    depends_on:
      ms-discovery:
        condition: service_started
  ms-teacher:
    image: ms-teacher:0.0.1
    mem_limit: 200m
    #    ports:
    #    - "7878:7878"
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
      - "ZIPKIN_URI=http://192.168.1.14:9411"
    depends_on:
      ms-discovery:
        condition: service_started
  ms-course:
    image: ms-course:0.0.1
    mem_limit: 200m
    #    ports:
    #    - "8743:8743"
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
      - "ZIPKIN_URI=http://192.168.1.14:9411"
    depends_on:
      ms-discovery:
        condition: service_started