version: "2.4"
networks:
  arquitectura:
    name: network-project
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
  software:
    name: network-config-server
    external: true
services:
  ms-discovery:
    image: ms-discovery:0.0.2
    mem_limit: 200m
    ports:
      - "8763:8763"
    networks:
      - software
      - arquitectura
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
    volumes:
      - "D:/Semestre 2-2021/Arquitectura del SW/tarea/logs/ms-discovery:/opt/arquitectura/logs"
  zipkin:
    image: openzipkin/zipkin
    mem_limit: 200m
    ports:
      - "9411:9411"
  ms-student:
    image: ms-student:0.0.4
    mem_limit: 200m
    ports:
      - "6945:6945"
    networks:
      - software
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
      - "ZIPKIN_URI=http://192.168.1.14:9411"
      - "CONFIG_URI=http://ms-config-server:8887"
    volumes:
    - /D/Semestre 2-2021/Arquitectura del SW/tarea/logs2/ms-student:/opt/arquitectura/logs
    depends_on:
      ms-discovery:
        condition: service_started
  ms-gateway:
    image: ms-gateway:0.0.4
    mem_limit: 200m
    ports:
      - "8181:8181"
    networks:
      - software
      - arquitectura
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
      - "ZIPKIN_URI=http://192.168.1.14:9411"
    depends_on:
      ms-discovery:
        condition: service_started
    volumes:
      - "D:/Semestre 2-2021/Arquitectura del SW/tarea/logs/ms-gateway:/opt/arquitectura/logs"

  ms-teacher:
    image: ms-teacher:0.0.4
    mem_limit: 200m
    ports:
      - "7878:7878"
    networks:
      - software
      - arquitectura
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
      - "ZIPKIN_URI=http://192.168.1.14:9411"
      - "CONFIG_URI=http://ms-config-server:8887"
    depends_on:
      ms-discovery:
        condition: service_started
    volumes:
      - "D:/Semestre 2-2021/Arquitectura del SW/tarea/logs/ms-teacher:/opt/arquitectura/logs"
  ms-course:
    image: ms-course:0.0.3
    mem_limit: 200m
    ports:
      - "8743:8743"
    networks:
      - software
      - arquitectura
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
      - "ZIPKIN_URI=http://192.168.1.14:9411"
      - "CONFIG_URI=http://ms-config-server:8887"
    depends_on:
      ms-discovery:
        condition: service_started
    volumes:
      - "D:/Semestre 2-2021/Arquitectura del SW/tarea/logs/ms-course:/opt/arquitectura/logs"