version: "2.4"

services:
  ms-discovery:
    image: ms-discovery:0.0.2
    mem_limit: 200m
    ports:
      - "8763:8763"
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
    volumes:
      - "/D/Semestre 2-2021/Arquitectura del SW/tarea/logs:/opt/arquitectura/logs"
  ms-config-server:
    image: ms-config-server:0.0.2
    mem_limit: 200m
    ports:
      - "8887:8887"
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
    depends_on:
      ms-discovery:
        condition: service_started
    volumes:
      - "/D/Semestre 2-2021/Arquitectura del SW/tarea/logs:/opt/arquitectura/logs"
  zipkin:
    image: openzipkin/zipkin
    mem_limit: 200m
    ports:
      - "9411:9411"
  ms-student:
    image: ms-student:0.0.2
    mem_limit: 200m
    #    ports:
    #    - "6945:6945"
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
      - "ZIPKIN_URI=http://192.168.1.14:9411"
    volumes:
    - "/D/Semestre 2-2021/Arquitectura del SW/tarea/logs:/opt/arquitectura/logs"
    depends_on:
      ms-discovery:
        condition: service_started
  ms-gateway:
    image: ms-gateway:0.0.4
    mem_limit: 200m
    ports:
      - "8181:8181"
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
      - "ZIPKIN_URI=http://192.168.1.14:9411"
    depends_on:
      ms-discovery:
        condition: service_started
    volumes:
      - "/D/Semestre 2-2021/Arquitectura del SW/tarea/logs:/opt/arquitectura/logs"

  ms-teacher:
    image: ms-teacher:0.0.3
    mem_limit: 200m
    #    ports:
    #    - "7878:7878"
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
      - "ZIPKIN_URI=http://192.168.1.14:9411"
    depends_on:
      ms-discovery:
        condition: service_started
    volumes:
      - "/D/Semestre 2-2021/Arquitectura del SW/tarea/logs:/opt/arquitectura/logs"
  ms-course:
    image: ms-course:0.0.2
    mem_limit: 200m
    #    ports:
    #    - "8743:8743"
    environment:
      - "EUREKA_URI=http://192.168.1.14:8763/eureka"
      - "ZIPKIN_URI=http://192.168.1.14:9411"
    depends_on:
      ms-discovery:
        condition: service_started
    volumes:
      - "/D/Semestre 2-2021/Arquitectura del SW/tarea/logs:/opt/arquitectura/logs"