spring:
  application:
    name: ms-discovery

server:
  port: ${SERVER_PORT:8763}

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${ERUEKA_URI:http://localhost:8763/eureka}
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 3000